addpath ("~/tools/YALMIP-master")
addpath ("~/tools/YALMIP-master/extras")
addpath ("~/tools/YALMIP-master/solvers")
addpath ("~/tools/YALMIP-master/modules")
addpath ("~/tools/YALMIP-master/modules/parametric")
addpath ("~/tools/YALMIP-master/modules/global")
addpath ("~/tools/YALMIP-master/operators")

addpath ("~/tools/sedumi")
addpath ("~/tools/sedumi/conversion")
addpath ("~/tools/sedumi/examples")

addpath ("~/tools/sdpt3")
addpath ("~/tools/sdpt3/Solver")
addpath ("~/tools/sdpt3/HSDSolver")
addpath ("~/tools/sdpt3/Solver/Mexfun")
addpath ("~/tools/sdpt3/Examples")